# -*- coding: utf-8 -*-
"""Копия блокнота "Untitled1.ipynb"

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YoQlN5QfZ03CzPI79ec_BYS9VoBQAk8n
"""

!pip install numpy

import numpy as np
import cv2

im="/content/IMG_0157.webp"
im=cv2.imread(im)
print(im)
print(im.ndim)
print(im.shape)
print(im.size)
print(im.dtype)

import numpy as np
import cv2
from google.colab.patches import cv2_imshow

path = "/content/image.jpg"
im = cv2.imread(path)

if im is not None:
    print("Свойства:")
    print(f"Форма: {im.shape}")
    print(f"Размер: {im.size}")
    print(f"Тип: {im.dtype}")

    new_width, new_height = 300, 200
    resized_im = cv2.resize(im, (new_width, new_height))
    print(f"Изменено: {resized_im.shape}")
    cv2_imshow(resized_im)

    height, width = im.shape[0], im.shape[1]
    cropped_im = im[0:height//2, 0:width//2]
    print(f"Обрезано: {cropped_im.shape}")
    cv2_imshow(cropped_im)

    flipped_im = cv2.flip(im, 1)
    print("Отражено")
    cv2_imshow(flipped_im)

    gray_im = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)
    print("Оттенки серого")
    cv2_imshow(gray_im)

    def add_gaussian_noise(image, mean=0, sigma=25):
        gauss = np.random.normal(mean, sigma, image.shape)
        noisy = image + gauss
        return np.clip(noisy, 0, 255).astype(np.uint8)

    def add_salt_and_pepper(image, salt_prob=0.01, pepper_prob=0.01):
        noisy = np.copy(image)
        num_salt = np.ceil(salt_prob * image.size)
        coords = [np.random.randint(0, i - 1, int(num_salt)) for i in image.shape]
        noisy[tuple(coords)] = 255
        num_pepper = np.ceil(pepper_prob * image.size)
        coords = [np.random.randint(0, i - 1, int(num_pepper)) for i in image.shape]
        noisy[tuple(coords)] = 0
        return noisy

    gaussian_noisy_im = add_gaussian_noise(gray_im)
    print("Гауссовский шум")
    cv2_imshow(gaussian_noisy_im)

    sp_noisy_im = add_salt_and_pepper(gray_im)
    print("Шум Соль и Перец")
    cv2_imshow(sp_noisy_im)

    b_channel, g_channel, r_channel = cv2.split(im)
    blue_im_only = cv2.merge([b_channel, np.zeros_like(b_channel), np.zeros_like(b_channel)])
    print("Синий канал")
    cv2_imshow(blue_im_only)

    ret, thresh_im = cv2.threshold(gray_im, 100, 255, cv2.THRESH_BINARY_INV)
    print("Пороговая обработка")
    cv2_imshow(thresh_im)

    kernel = np.ones((5,5), np.uint8)
    cleaned_im = cv2.morphologyEx(thresh_im, cv2.MORPH_OPEN, kernel, iterations=2)
    print("Морфологическое открытие")
    cv2_imshow(cleaned_im)

    contours, hierarchy = cv2.findContours(cleaned_im, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    print("Объекты:")
    output_im = im.copy()
    filtered_objects_found = 0
    for cnt in contours:
        area = cv2.contourArea(cnt)
        if area > 500:
            filtered_objects_found += 1
            M = cv2.moments(cnt)
            if M["m00"] != 0:
                cx = int(M["m10"] / M["m00"])
                cy = int(M["m01"] / M["m00"])
                print(f"Объект {filtered_objects_found}: Площадь={area:.2f}, Центр=({cx},{cy})")
                cv2.drawContours(output_im, [cnt], -1, (0, 255, 0), 2)
                cv2.circle(output_im, (cx, cy), 5, (0, 0, 255), -1)
            else:
                print(f"Объект {filtered_objects_found}: Площадь={area:.2f}")
    print(f"Всего обнаружено: {filtered_objects_found}")
    cv2_imshow(output_im)